In [1]:
import pandas as pd
from sklearn.datasets import load_files

PATH = 'dataset_news'
categories = ['automobiles','baseball', 'electronics', 'hockey','IBM hardware', 'motorbikes', 'use of guns', 'Mac hardware']
data = load_files(container_path=PATH,categories=categories, 
                                  shuffle=True, random_state=42)
print(data.target_names)
print(data.target)

['IBM hardware', 'Mac hardware', 'automobiles', 'baseball', 'electronics', 'hockey', 'motorbikes', 'use of guns']
[6 6 0 5 0 6 3 4 7 4 0 2 6 0 3 3 2 3 6 5 6 5 6 7 3 0 2 6 7 5 2 0 5 3 0 0 6
 3 7 7 1 2 1 3 5 5 4 5 6 5 2 1 6 2 3 3 4 3 1 1 4 7 6 3 2 4 0 7 3 0 5 1 7 0
 0 1 3 4 5 5 4 1 0 0 5 7 7 2 3 0 6 7 2 3 6 6 7 7 0 7 1 4 0 1 0 2 3 7 2 3 4
 5 0 0 7 1 5 7 2 2 3 3 1 7 2 2 5 0 2 6 6 2 0 6 3 5 7 3 6 4 2 5 4 2 0 4 1 3
 6 5 6 0 7 7 5 5 7 7 5 6 2 6 3 3 3 0 1 3 3 4 3 7 1 3 2 6 0 7 6 5 6 5 1 7 6
 0 5 6 4 6 4 4 2 5 5 0 6 1 7 5 2 1 0 5 1 0 0 6 3 4 7 1 0 1 1 0 4 1 2 7 7 1
 6 3 1 4 0 7 7 0 5 2 1 2 2 2 4 3 1 3 4 5 7 4 0 4 1 3 0 2 4 6 2 2 5 3 0 7 3
 3 0 3 7 6 5 3 2 0 5 7 0 0 4 2 4 1 5 5 2 4 4 3 3 4 4 1 6 3 1 2 5 7 0 6 4 1
 1 3 0 4 0 5 7 7 5 4 4 0 4 0 0 1 7 6 4 1 5 5 1 6 7 2 7 5 0 0 3 2 5 4 3 4 4
 6 7 3 4 0 2 0 2 5 6 7 6 3 6 2 2 0 5 3 5 2 1 6 3 1 0 4 6 2 0 5 1 2 2 0 7 1
 1 6 2 2 0 7 6 7 4 2 6 1 2 7 4 4 2 3 5 1 6 7 7 5 3 2 5 3 3 4 0 3 3 5 2 1 7
 6 1 0 5 4 1 4 7 5 7 1 3 4 5 7 1 1 6 6 1 5 0 4 7 4 3 3 7 1 3 

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer(stop_words="english")
X_train_counts = count_vect.fit_transform(data.data).todense()
print(X_train_counts.shape)
print(X_train_counts)
# count_vect.vocabulary_.get(u'hockey')

(800, 14551)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [3]:
import numpy as np
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(np.asarray(X_train_counts)).todense()
X_train_tfidf.shape

(800, 14551)

# 2.

In [4]:
from sklearn.naive_bayes import MultinomialNB
#used when all features follow a multinomial distribution
X=np.asarray(X_train_tfidf)
mnb = MultinomialNB(alpha=1.0) 
mnb.fit (X,data.target) 

y_pred = mnb.predict(X)
print ("Number of mislabeled points out of a total %d points : %d" % \
(len(data.target),(data.target != y_pred).sum()))

Number of mislabeled points out of a total 800 points : 18


In [5]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X,data.target)

y_pred = gnb.predict(X)
print ("Number of mislabeled points out of a total %d points : %d" % \
(len(data.target),(data.target != y_pred).sum()))

Number of mislabeled points out of a total 800 points : 26


# 3a

In [6]:
import numpy as np
from sklearn.model_selection import KFold

kf = KFold(n_splits=10)
counter = 1
error_data = 0
for train, test in kf.split(X):
    print ("%d Fold" % counter)
#     print ("%s %s" % (train, test))
#     print (np.array(X)[train])
#     print (np.array(X)[test])
#     print(data.target[train])
#     print(data.target[test])
    counter += 1
    # train and predict using your model
    # count the accuracy
    mnb.fit(np.array(X)[train],data.target[train])
    y_pred = mnb.predict(np.array(X)[test])
    print ("Number of mislabeled points out of a total %d points : %d" % \
    (len(data.target[test]),(data.target[test] != y_pred).sum()))
    error_data+=(data.target[test] != y_pred).sum()
accuracy=1-error_data/(len(data.target[test])*10)
print("Average accuracy of MultinomialNB is %f" % accuracy )
# print the average accuracy

1 Fold
Number of mislabeled points out of a total 80 points : 15
2 Fold
Number of mislabeled points out of a total 80 points : 12
3 Fold
Number of mislabeled points out of a total 80 points : 20
4 Fold
Number of mislabeled points out of a total 80 points : 19
5 Fold
Number of mislabeled points out of a total 80 points : 14
6 Fold
Number of mislabeled points out of a total 80 points : 20
7 Fold
Number of mislabeled points out of a total 80 points : 15
8 Fold
Number of mislabeled points out of a total 80 points : 24
9 Fold
Number of mislabeled points out of a total 80 points : 18
10 Fold
Number of mislabeled points out of a total 80 points : 18
Average accuracy of MultinomialNB is 0.781250


In [7]:
kf = KFold(n_splits=10)
counter = 1
error_data = 0
for train, test in kf.split(X):
    print ("%d Fold" % counter)
    counter += 1
    # train and predict using your model
    # count the accuracy
    gnb.fit(np.array(X)[train],data.target[train])
    y_pred = gnb.predict(np.array(X)[test])
    print ("Number of mislabeled points out of a total %d points : %d" % \
    (len(data.target[test]),(data.target[test] != y_pred).sum()))
    error_data+=(data.target[test] != y_pred).sum()
accuracy=1-error_data/(len(data.target[test])*10)
print("Average accuracy of GaussianNB is %f" % accuracy )
# print the average accuracy

1 Fold
Number of mislabeled points out of a total 80 points : 23
2 Fold
Number of mislabeled points out of a total 80 points : 19
3 Fold
Number of mislabeled points out of a total 80 points : 25
4 Fold
Number of mislabeled points out of a total 80 points : 22
5 Fold
Number of mislabeled points out of a total 80 points : 18
6 Fold
Number of mislabeled points out of a total 80 points : 27
7 Fold
Number of mislabeled points out of a total 80 points : 22
8 Fold
Number of mislabeled points out of a total 80 points : 25
9 Fold
Number of mislabeled points out of a total 80 points : 23
10 Fold
Number of mislabeled points out of a total 80 points : 20
Average accuracy of GaussianNB is 0.720000


# 3b

In [8]:
import random
correct=0
for i in range (len(data.target)):
    correct+=(data.target[i] == random.randint(0, 7)).sum()
accuracy=correct/len(data.target)
print("Average accuracy of  random classifier is %f" % accuracy )

Average accuracy of  random classifier is 0.112500


# 3c

In [9]:
count_vect2 = CountVectorizer()
X_train_counts2 = count_vect2.fit_transform(data.data).todense()
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(np.asarray(X_train_counts2)).todense()
X_withSW = np.asarray(X_train_tfidf)
print(X_withSW.shape)

(800, 14842)


In [10]:
kf = KFold(n_splits=10)
counter = 1
error_data = 0
mnb = MultinomialNB(alpha=1.0) 
for train, test in kf.split(X_withSW):
    print ("%d Fold" % counter)
    counter += 1
    # train and predict using your model
    # count the accuracy

    mnb.fit(np.array(X_withSW)[train],data.target[train])
    y_pred = mnb.predict(np.array(X_withSW)[test])
    print ("Number of mislabeled points out of a total %d points : %d" % \
    (len(data.target[test]),(data.target[test] != y_pred).sum()))
    error_data+=(data.target[test] != y_pred).sum()
accuracy=1-error_data/(len(data.target[test])*10)
print("Average accuracy of MultinomialNB with stopwords is %f" % accuracy )
# print the average accuracy

1 Fold
Number of mislabeled points out of a total 80 points : 27
2 Fold
Number of mislabeled points out of a total 80 points : 17
3 Fold
Number of mislabeled points out of a total 80 points : 20
4 Fold
Number of mislabeled points out of a total 80 points : 28
5 Fold
Number of mislabeled points out of a total 80 points : 21
6 Fold
Number of mislabeled points out of a total 80 points : 27
7 Fold
Number of mislabeled points out of a total 80 points : 18
8 Fold
Number of mislabeled points out of a total 80 points : 32
9 Fold
Number of mislabeled points out of a total 80 points : 23
10 Fold
Number of mislabeled points out of a total 80 points : 29
Average accuracy of MultinomialNB with stopwords is 0.697500


# 3d

In [11]:
categories1 = ['hockey', 'use of guns', 'Mac hardware']
data1 = load_files(container_path=PATH,categories=categories1, 
                                  shuffle=True, random_state=42)
print(data1.target_names)
print(data1.target)
count_vect = CountVectorizer(stop_words="english")
X_train_counts = count_vect.fit_transform(data1.data).todense()
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(np.asarray(X_train_counts)).todense()
X_withSW = np.asarray(X_train_tfidf)
print(X_withSW.shape)
kf = KFold(n_splits=10)
counter = 1
error_data = 0
mnb = MultinomialNB(alpha=1.0) 
for train, test in kf.split(X_withSW):
    print ("%d Fold" % counter)
    counter += 1
    # train and predict using your model
    # count the accuracy

    mnb.fit(np.array(X_withSW)[train],data1.target[train])
    y_pred = mnb.predict(np.array(X_withSW)[test])
    print ("Number of mislabeled points out of a total %d points : %d" % \
    (len(data1.target[test]),(data1.target[test] != y_pred).sum()))
    error_data+=(data1.target[test] != y_pred).sum()
accuracy=1-error_data/(len(data1.target[test])*10)
print("Task1:Average accuracy of MultinomialNB with stopwords is %f" % accuracy )
# print the average accuracy

['Mac hardware', 'hockey', 'use of guns']
[2 2 1 0 2 2 1 1 0 1 2 0 2 0 1 2 2 2 1 1 0 1 2 2 1 0 2 2 1 2 0 1 0 0 2 1 0
 0 0 0 0 0 2 0 0 0 2 2 1 2 1 1 2 0 2 2 0 0 1 0 2 0 0 1 1 0 0 2 0 1 1 1 2 1
 1 2 0 0 0 2 1 1 0 1 0 1 1 0 0 0 1 1 0 2 0 0 1 1 2 0 2 0 0 1 2 2 1 0 1 0 1
 2 0 2 2 1 1 2 1 2 0 1 1 1 1 2 0 1 1 2 1 1 1 1 2 2 1 1 1 0 1 1 1 1 2 2 1 0
 0 0 2 1 2 1 2 2 2 0 1 0 2 1 0 0 0 1 2 2 1 0 0 2 2 0 0 2 1 0 2 1 2 0 2 2 1
 2 2 1 0 0 0 1 2 2 2 0 2 2 0 2 0 1 0 2 1 2 2 1 0 1 1 2 0 0 2 0 0 2 1 0 1 2
 2 1 0 2 1 0 2 2 0 2 2 2 1 0 0 0 2 2 2 2 1 0 2 1 1 2 2 0 1 0 1 0 1 1 0 0 2
 0 0 0 2 0 0 1 2 1 2 2 0 0 1 1 2 1 1 0 0 2 2 0 1 2 1 2 1 1 1 0 0 2 1 2 0 1
 0 1 2 1]
(300, 8159)
1 Fold
Number of mislabeled points out of a total 30 points : 4
2 Fold
Number of mislabeled points out of a total 30 points : 2
3 Fold
Number of mislabeled points out of a total 30 points : 2
4 Fold
Number of mislabeled points out of a total 30 points : 1
5 Fold
Number of mislabeled points out of a total 30 points : 2
6 Fold
Number of

In [12]:
categories2 = ['electronics','IBM hardware', 'Mac hardware']
data2 = load_files(container_path=PATH,categories=categories2, 
                                  shuffle=True, random_state=42)
print(data2.target_names)
print(data2.target)
count_vect = CountVectorizer(stop_words="english")
X_train_counts = count_vect.fit_transform(data2.data).todense()
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(np.asarray(X_train_counts)).todense()
X_withSW = np.asarray(X_train_tfidf)
print(X_withSW.shape)
kf = KFold(n_splits=10)
counter = 1
error_data = 0
mnb = MultinomialNB(alpha=1.0) 
for train, test in kf.split(X_withSW):
    print ("%d Fold" % counter)
    counter += 1
    # train and predict using your model
    # count the accuracy

    mnb.fit(np.array(X_withSW)[train],data1.target[train])
    y_pred = mnb.predict(np.array(X_withSW)[test])
    print ("Number of mislabeled points out of a total %d points : %d" % \
    (len(data2.target[test]),(data2.target[test] != y_pred).sum()))
    error_data+=(data2.target[test] != y_pred).sum()
accuracy=1-error_data/(len(data2.target[test])*10)
print("Task2:Average accuracy of MultinomialNB with stopwords is %f" % accuracy )
# print the average accuracy

['IBM hardware', 'Mac hardware', 'electronics']
[2 2 1 0 2 2 1 1 0 1 2 0 2 0 1 2 2 2 1 1 0 1 2 2 1 0 2 2 1 2 0 1 0 0 2 1 0
 0 0 0 0 0 2 0 0 0 2 2 1 2 1 1 2 0 2 2 0 0 1 0 2 0 0 1 1 0 0 2 0 1 1 1 2 1
 1 2 0 0 0 2 1 1 0 1 0 1 1 0 0 0 1 1 0 2 0 0 1 1 2 0 2 0 0 1 2 2 1 0 1 0 1
 2 0 2 2 1 1 2 1 2 0 1 1 1 1 2 0 1 1 2 1 1 1 1 2 2 1 1 1 0 1 1 1 1 2 2 1 0
 0 0 2 1 2 1 2 2 2 0 1 0 2 1 0 0 0 1 2 2 1 0 0 2 2 0 0 2 1 0 2 1 2 0 2 2 1
 2 2 1 0 0 0 1 2 2 2 0 2 2 0 2 0 1 0 2 1 2 2 1 0 1 1 2 0 0 2 0 0 2 1 0 1 2
 2 1 0 2 1 0 2 2 0 2 2 2 1 0 0 0 2 2 2 2 1 0 2 1 1 2 2 0 1 0 1 0 1 1 0 0 2
 0 0 0 2 0 0 1 2 1 2 2 0 0 1 1 2 1 1 0 0 2 2 0 1 2 1 2 1 1 1 0 0 2 1 2 0 1
 0 1 2 1]
(300, 6869)
1 Fold
Number of mislabeled points out of a total 30 points : 13
2 Fold
Number of mislabeled points out of a total 30 points : 7
3 Fold
Number of mislabeled points out of a total 30 points : 6
4 Fold
Number of mislabeled points out of a total 30 points : 11
5 Fold
Number of mislabeled points out of a total 30 points : 13
6 Fold
