In [1]:
from sklearn.cluster import KMeans

In [2]:
import numpy as np
import pandas as pd

df_data = pd.read_csv('clustering_data.csv')
select_col= df_data.columns[1:]
data = np.array(df_data[select_col])
data

array([[ -4.7557   ,   4.00509  ,   3.58155  ,  -0.395257 ,   0.768624 ,
          1.12594  ,  -0.237274 ,  -1.91728  ,   0.706794 ,   0.957592 ,
         -0.0206825,   6.34668  ,  -2.82923  ,   1.68118  ,  -4.10586  ,
          4.63801  ,   1.46898  ,   2.74809  ,  -0.0228676,   1.87709  ,
         -0.70247  ,   2.44804  ,  -3.13752  ,  -1.13863  ,  -0.0651749],
       [ -3.2019   ,   5.65488  ,  -1.44928  ,   0.693878 ,   0.574788 ,
          1.50561  ,  -1.42566  ,   0.467675 ,  -2.90853  ,   0.0558659,
         -3.65062  ,   0.99398  ,  -2.76886  ,  -1.29434  ,  -3.80463  ,
          0.93633  ,   0.122649 ,   3.74037  ,  -0.92452  ,   4.33917  ,
          3.06093  ,   4.88284  ,  -0.0691085,  -0.353045 ,   1.15721  ],
       [ -0.55384  ,   1.92791  ,   0.529256 ,   1.80451  ,   2.05676  ,
         -0.869652 ,  -3.18936  ,   3.37173  ,   3.67084  ,  -4.0242   ,
         -0.9911   ,  -0.853207 ,  -1.21903  ,  -6.0285   ,  -3.45091  ,
          2.06707  ,   1.0505   ,   3.03001  ,   

In [3]:
kmeans_default = KMeans(init='random', n_clusters=8, max_iter=300, n_init=10).fit(data)
kmeans_init = KMeans(init='k-means++', n_clusters=8, max_iter=300, n_init=10).fit(data)
kmeans_n_init = KMeans(init='random', n_clusters=8, max_iter=300, n_init=100).fit(data)

In [4]:
kmeans_default.inertia_

1709.5994921026906

In [5]:
kmeans_init.inertia_

1582.8948903852593

In [6]:
kmeans_n_init.inertia_

1630.1433044039331

In [7]:
kmeans_default.labels_

array([1, 7, 2, 0, 6, 5, 6, 1, 6, 7, 6, 6, 7, 5, 7, 3, 7, 6, 6, 5, 4, 2,
       6, 2, 6, 1, 5, 5, 3, 3])

In [8]:
kmeans_init.labels_

array([0, 0, 7, 2, 3, 1, 3, 6, 1, 2, 4, 4, 0, 1, 2, 4, 5, 4, 4, 1, 1, 7,
       4, 7, 4, 0, 1, 1, 4, 1])

In [9]:
kmeans_n_init.labels_

array([1, 1, 7, 6, 0, 2, 0, 1, 2, 1, 2, 2, 1, 2, 0, 3, 5, 2, 1, 2, 2, 4,
       1, 7, 1, 1, 2, 2, 1, 1])